#!/bin/bash
echo 'MariaDB[(none)]> SELECT user,authentication_string,plugin,host FROM mysql.user;'
echo ''
echo '+------------------+-------------------------------------------+-----------------------+-----------+ '
echo '| user             | authentication_string                     | plugin                | host      | '
echo '+------------------+-------------------------------------------+-----------------------+-----------+ '
echo '| root             | *ODLHT9E91T1HEM7D4I9W5QC4GEDL2PZZ0DS9U4CG | mysql_native_password | localhost | '
echo '| mysql.session    | *THISISNOTAVALIDPASSWORDTHATCANBEUSEDHERE | mysql_native_password | localhost | '
echo '| mysql.sys        | *THISISNOTAVALIDPASSWORDTHATCANBEUSEDHERE | mysql_native_password | localhost | '
echo '| debian-sys-maint | *VMV1FV3J4I2WANBB7WRYHPBHS74QQ4LZNIAX3TXC | mysql_native_password | localhost | '
echo '+------------------+-------------------------------------------+-----------------------+-----------+ '
echo '4 rows in set (0.00 sec)'
